### ISSUE TITLE
Pits of Inferno rewards not working

### ISSUE THREAD

**Issue by oualid6496** [opentibiabr/otservbr-global-archived#1373]
**Describe the bug**
When trying to obtain any of the rewards (except the weapons) you'll open the chest and see the item inside it instead of actually bugging. It also gives an error in the console.

**To Reproduce**
Just open any reward (except for the weapons) of the Pits of Inferno Quest

**Expected behavior**
Obtaining the reward without errors

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Also the monsters "Eye of the Seven" in the Ushuriels room in the Inquisition Quest move even tho im pretty sure they shouldn't.

**Comment by oualid6496** [comment]
Also there is a typo in the creaturescript.xml file "IquisitionBossKill" should be "InquisitionBossKill"
Same typo is also in login_events

**Comment by dudantas** [comment]
> Also there is a typo in the creaturescript.xml file "IquisitionBossKill" should be "InquisitionBossKill"
> Same typo is also in login_events

But, pits of inferno is related to inquisition?

**Comment by oualid6496** [comment]
Not really just thought that I shouldn't make a new issue just for a typo :P

**Comment by dudantas** [comment]
> Not really just thought that I shouldn't make a new issue just for a typo :P

Ok

**Comment by oualid6496** [comment]
Problem with Poi rewards has something to do with the new unique ids systems. When im using another unique id it seems to be working fine.

**Comment by nickolasdeluca** [comment]
R u sure about this? in my OT we did POI last weekend and it worked well... at least the rewards did. There were problems all around the map tho.

**Comment by oualid6496** [comment]
Yea im sure. Update the distro and see. It has to do with the commit of June 16th Eduardo already knows about it

**Comment by nickolasdeluca** [comment]
Damn, I updated mine this weekend, shit.

**Comment by nickolasdeluca** [comment]
hey @oualid6496, can you add in this issue that the drawbridge lever is also not working?

**Comment by oualid6496** [comment]
I think it's better to create a new Issue for that since I don't know what you mean

**Comment by lucas-caminha** [comment]
doesn't work here too, did you fix it?

**Comment by nickolasdeluca** [comment]
> doesn't work here too, did you fix it?

what doesn't work?

**Comment by lucas-caminha** [comment]
Pits of Inferno rewards not working. The same that happened to him

**Comment by oualid6496** [comment]
Yea by using another unique id. Some unique ids are reserved for certain function. Same goes for the poi rewards. Try changing them to 1050 and add 1 for every other chest. This should be a temporary fix.

**Comment by lBaah** [comment]
Which error is printed at the console?

**Comment by lucas-cmh** [comment]
![rewardbug](https://user-images.githubusercontent.com/38120031/85956820-c87e3480-b95e-11ea-9dee-079d2f95bd98.png)

**Comment by lucas-caminha** [comment]
![rewardbug](https://user-images.githubusercontent.com/38120031/85956884-388cba80-b95f-11ea-9b10-f65a8f541829.png)

**Comment by lBaah** [comment]
Update your script:
https://github.com/opentibiabr/otservbr-global/blob/develop/data/scripts/actions/system/quest_reward_container.lua
There is no UniqueTable variable there

**Comment by lucas-caminha** [comment]
![moreerro](https://user-images.githubusercontent.com/38120031/85957932-fb78f600-b967-11ea-83ca-2b32c87bf050.png)

after the commit on the 16th, several quest errors appeared. my script was already updated.

**Comment by lBaah** [comment]
https://github.com/opentibiabr/otservbr-global/blob/develop/data/startup/tables/chest.lua#L29
Looks like you forgotten something there :)
Review what have you changed and remember errors are expected since the server is still being developed, so NEVER apply any change directly on the server you are running. Test it in the first place, if it works THEN you add to your server. :)

Also download a fresh version of the actual repo and test it again since i'm not doing that :+1:

**Comment by thatmichaelguy** [comment]
Fresh version of actual repo has this issue (or a variant of it) - lots of chests that were using AID 2000 (quest_system1.lua) but have not been moved to the new chests.lua table do not work anymore.
Examples include but are not limited to: POI soft boots etc., INQ platinum coins, backpacks etc., some tomes of knowledge
I am sure there are many, many more.
quest_system1.lua is not executing at all in these cases - only the quest_reward_x system even though it hasn't been added to chest.lua tables (which is why it fails)

**Comment by dudantas** [comment]
> Fresh version of actual repo has this issue (or a variant of it) - lots of chests that were using AID 2000 (quest_system1.lua) but have not been moved to the new chests.lua table do not work anymore.
> Examples include but are not limited to: POI soft boots etc., INQ platinum coins, backpacks etc., some tomes of knowledge
> I am sure there are many, many more.
> quest_system1.lua is not executing at all in these cases - only the quest_reward_x system even though it hasn't been added to chest.lua tables (which is why it fails)

The quest system that follows the 2000/2001 action standard has not been changed
The system added by the startup is independent, it works exclusively by the table and does not alter or change anything in those that are in the startup folder

**Comment by thatmichaelguy** [comment]
I can see the intention and I can't see a reason for the standard AID 2000 quest_system1.lua to not be executing - but it isn't.

**Comment by oualid6496** [comment]
It has to do with the unique ids they are being reserved in some other script I dont remember which one. But try to change the uid to for example 1040 and it should be working normally

**Comment by thatmichaelguy** [comment]
I've added the critical chests (poi, inq) to chests.lua on my production server and it works okay, but it is just a temporary fix I guess because the UID's will have to change when git is updated.

I've just launched a public test server with 100% fresh git pull - no edits at all - can confirm the issue still exists. AID 2000 quest_system1.lua is not executing. Happy to give anyone else access if they want to take a look. Can message me on Discord Michael#4463

This is the error:
``Lua Script Error: [Scripts Interface]
/home/global/server/data/scripts/actions/system/quest_reward_container.lua:callback
...r/data/scripts/actions/system/quest_reward_container.lua:6: attempt to index local 'setting' (a nil value)
stack traceback:
        [C]: in function '__index'
        ...r/data/scripts/actions/system/quest_reward_container.lua:6: in function <...r/data/scripts/actions/system/quest_reward_container.lua:4>``

In addition to this issue, the new quest_reward_x system is not handling stackable items with quantities > 1 correctly. It displays the message, for example "100 platinum coins" correctly, but doesn't actually give you the items.

**Comment by dudantas** [comment]
> I've added the critical chests (poi, inq) to chests.lua on my production server and it works okay, but it is just a temporary fix I guess because the UID's will have to change when git is updated.
> 
> I've just launched a public test server with 100% fresh git pull - no edits at all - can confirm the issue still exists. AID 2000 quest_system1.lua is not executing. Happy to give anyone else access if they want to take a look. Can message me on Discord Michael#4463
> 
> This is the error:
> `Lua Script Error: [Scripts Interface] /home/global/server/data/scripts/actions/system/quest_reward_container.lua:callback ...r/data/scripts/actions/system/quest_reward_container.lua:6: attempt to index local 'setting' (a nil value) stack traceback: [C]: in function '__index' ...r/data/scripts/actions/system/quest_reward_container.lua:6: in function <...r/data/scripts/actions/system/quest_reward_container.lua:4>`
> 
> In addition to this issue, the new quest_reward_x system is not handling stackable items with quantities > 1 correctly. It displays the message, for example "100 platinum coins" correctly, but doesn't actually give you the items.

Okay, I already found the problem. Soon I will go up the correction.
